





CREATE PROCEDURE [DBO].[USP_ERR_LOG]
	@E_PROC AS NVARCHAR(128),
	@E_PLAT as VARCHAR(128),
	@E_NBR AS INTEGER,
	@E_LINE AS INTEGER,
	@E_SEV AS INTEGER,
	@E_ST AS INTEGER,
	@E_MSG AS NVARCHAR(4000),
	@OS_USR AS VARCHAR(255),
	@RTN INT = Null OUTPUT
AS

SET NOCOUNT ON

BEGIN TRY
	BEGIN
		INSERT INTO AM.PROCEDURE_ERROR_LOG(ERR_PROCEDURE, ERR_PLATFORM, ERR_NUMBER, ERR_LINE, ERR_SEVERITY,ERR_STATE, ERR_MESSAGE, USER_OSUSER,CREATED_DTE)
					VALUES(@E_PROC, @E_PLAT, @E_NBR, @E_LINE, @E_SEV, @E_ST, @E_MSG, @OS_USR, GETDATE())

		SET @RTN = SCOPE_IDENTITY()
	RETURN @RTN
	END
END TRY
BEGIN CATCH
	SET @RTN = -1
	RETURN @RTN
END CATCH










