--PG: Adding File Header on 06/14/2018

CREATE FUNCTION [AM].[UDF_QM_THRESH_TO_SCALE] ()
	RETURNS TINYINT

	AS

	BEGIN
			
		DECLARE @STT TINYINT, @StartDate datetime
		DECLARE @RUN_SCALE INT  = ISNULL((SELECT SUM(ACM.ART_SCALE_VALUE) as 'SCALE' FROM AM.ARTIFACT_CTRL_MASTER ACM WHERE LAST_STATUS_CODE_VALUE_ID = 1), 0)
		DECLARE @RUN_THRESH INT = ISNULL((SELECT KeyValueInt CNT FROM AM.ENVIRONMENT_VAR_MASTER WHERE ID = 1),0)

		SET @STT = @RUN_THRESH - @RUN_SCALE
		SET @StartDate = GetDate()
		RETURN @STT

	END 




