CREATE PROCEDURE [DASH].[USP_BATCH_SCHD_COUNTS]
AS

SET NOCOUNT ON
BEGIN
	SELECT [SCHEDULE_TYPE_VALUE_ID], [CNT],[Complete]
	FROM [DASH].[v_BATCH_SCHD_COUNTS]
	ORDER BY [SCHEDULE_TYPE_VALUE_ID]
END

