CREATE PROCEDURE [AM].[USP_MERGE_FRAMEWORK_CHANGES_CCA]
@CHANGE_ID INT,
@CHANGE_LOAD_ID INT
AS

BEGIN 

MERGE INTO CHG.CHANGE_CONTROL_ARTIFACT AS target
USING
(SELECT * 
FROM CHG.STAGE_CHANGE_CONTROL_ARTIFACT
 WHERE CHG_ID = @CHANGE_ID AND LAST_CHG_LOAD_ID =  @CHANGE_LOAD_ID  ) AS source
  ON (target.CHG_ID = source.CHG_ID AND target.ART_CTRL_MASTER_ID = source.ART_CTRL_MASTER_ID)

 WHEN MATCHED THEN
 UPDATE SET
-- target.CHG_ID = source.CHG_ID,
--target.ART_CTRL_MASTER_ID = source.ART_CTRL_MASTER_ID,
target.IS_ACTIVE_IND = source.IS_ACTIVE_IND,
target.CREATED_DTE = source.CREATED_DTE,
target.CREATED_BY = source.CREATED_BY,
target.LAST_UPDT_DTE =  getdate(), --current date
target.LAST_UPDT_BY = CURRENT_USER, -- current user
target.CREATED_ARC_DTE = source.CREATED_ARC_DTE, --Not sure of the value to be populated
target.LAST_CHG_LOAD_ID = @CHANGE_LOAD_ID


WHEN NOT MATCHED BY TARGET THEN        
INSERT(CHG_ID,ART_CTRL_MASTER_ID,IS_ACTIVE_IND,CREATED_DTE,CREATED_BY,LAST_UPDT_DTE,LAST_UPDT_BY,CREATED_ARC_DTE,LAST_CHG_LOAD_ID)
VALUES(CHG_ID,ART_CTRL_MASTER_ID,IS_ACTIVE_IND,GETDATE(),CURRENT_USER,NULL,NULL,CREATED_ARC_DTE,@CHANGE_LOAD_ID)

;

END
