CREATE PROCEDURE [AM].[USP_UI_DELETE_HARD_ARTIFACT_DEPENDENCY]
	@ART_CTRL_MASTER_ID INTEGER,			--<=Requried
	@REFERENCED_CTRL_MASTER_ID INTEGER,		--<=Requried
	@RTN AS INTEGER = NULL OUTPUT			--<=Optional - No need to send defaults to 0 and then returns message based on success
AS

	SET NOCOUNT ON
	
	DECLARE @LAST_UPDT_DTE DATETIME = GETDATE()
	DECLARE @LAST_UPDT_BY VARCHAR(100) = SYSTEM_USER
		
	BEGIN TRY
		
		IF (SELECT COUNT(ART_CTRL_MASTER_ID) FROM AM.ARTIFACT_DEPENDENCY WHERE ART_CTRL_MASTER_ID = @ART_CTRL_MASTER_ID 	AND REFERENCED_CTRL_MASTER_ID = @REFERENCED_CTRL_MASTER_ID) <> 1
			BEGIN
				RAISERROR ('The record was not found please check the ART_CTRL_MASTER_ID and REFERENCED_CTRL_MASTER_ID supplied',16,1)
			END		
			 
		DELETE FROM AM.ARTIFACT_DEPENDENCY 
		WHERE ART_CTRL_MASTER_ID = @ART_CTRL_MASTER_ID 	AND REFERENCED_CTRL_MASTER_ID = @REFERENCED_CTRL_MASTER_ID		

		SET @RTN = 1
		RETURN @RTN --Positive Return

	END TRY
	BEGIN CATCH
		 DECLARE @ProcName AS NVARCHAR(128) = ISNULL(ERROR_PROCEDURE(), 'UNKNOWN');
		 DECLARE @ER_PLAT as VARCHAR(128) = 'MSSQL DB ENGINE'
		 DECLARE @ER_NBR AS INTEGER = ISNULL(ERROR_NUMBER(),0)
		 DECLARE @ER_LINE AS INTEGER = ISNULL(ERROR_LINE(),0)
		 DECLARE @ER_SEV AS INTEGER = ISNULL(ERROR_SEVERITY(),0)
		 DECLARE @ER_ST AS INTEGER = ISNULL(ERROR_STATE(),0)
		 DECLARE @ER_MSG AS NVARCHAR(4000) = ISNULL(ERROR_MESSAGE(), 'A MESSAGE WAS NOT PROVIDED');
		 DECLARE @ER_USR AS VARCHAR(255) = ISNULL(CURRENT_USER, 'UNKONWN')

		 EXECUTE @RTN =  AM.USP_ERR_LOG @ProcName, @ER_PLAT, @ER_NBR, @ER_LINE, @ER_SEV, @ER_ST,@ER_MSG, @ER_USR	
		 RETURN @RTN --Returns LOG_ID From [AM].[PROCEDURE_ERROR_LOG]  as a negitive integer
	END CATCH;





