CREATE TABLE [AM].[ARTIFACT_QUEUE_RUNTIME] (
    [ART_CTRL_MASTER_ID]               INT      NOT NULL,
    [AVG_QUEUE_RUNTIME_SECONDS_7_Day]  INT      NOT NULL,
    [AVG_QUEUE_RUNTIME_SECONDS_30_Day] INT      NOT NULL,
    [AVG_QUEUE_RUNTIME_SECONDS_60_Day] INT      NOT NULL,
    [AVG_QUEUE_RUNTIME_SECONDS_90_Day] INT      NOT NULL,
    [IS_ALERTED]                       BIT      NULL,
    [CREATED_DTE]                      DATETIME NOT NULL,
    [LAST_UPDT_DTE]                    DATETIME NULL,
    CONSTRAINT [PK_ART_QUE_RUNTIME-ART_CTRL_MASTER_ID] PRIMARY KEY CLUSTERED ([ART_CTRL_MASTER_ID] ASC) WITH (FILLFACTOR = 95)
);

