CREATE TABLE [AM].[ARTIFACT_DEPLOYMENT] (
    [ART_DEPLOYMENT_ID]    INT            IDENTITY (1, 1) NOT NULL,
    [ART_CTRL_MASTER_ID]   INT            NOT NULL,
    [ART_DEPLOYMENT_PATH]  VARCHAR (400)  NULL,
    [ART_FOLDER_VALUE_ID]  INT            NULL,
    [ART_PROJECT_VALUE_ID] INT            NULL,
    [DEPLOYMENT_COMMENTS]  VARCHAR (1000) NULL,
    [ART_VALIDATED]        BIT            NULL,
    [IS_ENABLED_IND]       BIT            CONSTRAINT [DF__ARTIFACT___IS_EN__3C34F16F] DEFAULT ('FALSE') NOT NULL,
    [LOAD_ID]              INT            NULL,
    [CREATED_DTE]          DATETIME       CONSTRAINT [DF__ARTIFACT___CREAT__3B40CD36] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]           VARCHAR (50)   NOT NULL,
    [LAST_UPDT_DTE]        DATETIME       NULL,
    [LAST_UPDT_BY]         VARCHAR (50)   NULL,
    [LAST_CHG_LOAD_ID]     INT            NULL,
    CONSTRAINT [PK_ARTIFACT_DEPLOYMENT-ART_DEPLOYMENT_ID] PRIMARY KEY CLUSTERED ([ART_DEPLOYMENT_ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [UNQ_ARTIFACT_DEPLOYMENT-ART_ID] UNIQUE NONCLUSTERED ([ART_CTRL_MASTER_ID] ASC) WITH (FILLFACTOR = 95)
);

