CREATE TABLE [AM].[ARTIFACT_CTRL_DETAIL] (
    [LOG_ID]                      INT            IDENTITY (1, 1) NOT NULL,
    [ART_CTRL_MASTER_ID]          INT            NOT NULL,
    [ART_NME]                     VARCHAR (100)  NOT NULL,
    [EXEC_ID]                     INT            NULL,
    [LOAD_ID]                     INT            NOT NULL,
    [STATUS_CODE_VALUE_ID]        INT            NOT NULL,
    [EXEC_STATUS_VALUE_ID]        TINYINT        NULL,
    [ART_GROUP_VALUE_ID]          TINYINT        NOT NULL,
    [ART_PROCESS_DESC]            VARCHAR (1000) NULL,
    [BATCH_DTE]                   DATE           NOT NULL,
    [ART_BATCH_RETRY_COUNTER]     TINYINT        NOT NULL,
    [ART_BATCH_RETRY_THRESHOLD]   TINYINT        NOT NULL,
    [START_TIME]                  DATETIME       NULL,
    [END_TIME]                    DATETIME       NULL,
    [SOURCE_NME]                  VARCHAR (100)  NULL,
    [SOURCE_TOTAL_RECORDS]        DECIMAL (10)   NULL,
    [SOURCE_NEW_RECORDS]          DECIMAL (10)   NULL,
    [SOURCE_CHANGE_RECORDS]       DECIMAL (10)   NULL,
    [SOURCE_DELETE_RECORDS]       DECIMAL (10)   NULL,
    [TARGET_NME]                  VARCHAR (100)  NULL,
    [TARGET_TOTAL_RECORDS_BEFORE] DECIMAL (10)   NULL,
    [TARGET_NEW_RECORDS]          DECIMAL (10)   NULL,
    [TARGET_CHANGE_RECORDS]       DECIMAL (10)   NULL,
    [TARGET_DELETE_RECORDS]       DECIMAL (10)   NULL,
    [TARGET_UNCHANGED_RECORDS]    DECIMAL (10)   NULL,
    [TARGET_FAILED_RECORDS]       DECIMAL (10)   NULL,
    [TARGET_TOTAL_RECORDS_AFTER]  DECIMAL (10)   NULL,
    [LOAD_MESSAGE]                VARCHAR (4000) NULL,
    [USER_OSUSER]                 VARCHAR (255)  NULL,
    [CREATED_DTE]                 DATETIME       NOT NULL,
    [IS_INCREMENTAL_LOAD]         BIT            NULL,
    [LOAD_START_VALUE]            VARCHAR (200)  NULL,
    [LOAD_END_VALUE]              VARCHAR (200)  NULL,
    CONSTRAINT [PK_ARTIFACT_CTRL_DETAIL-LOG_ID1] PRIMARY KEY CLUSTERED ([LOG_ID] ASC) WITH (FILLFACTOR = 95)
);

