CREATE TABLE [AM].[ARTIFACT_CODE_VALUE] (
    [CODE_VALUE_ID]   INT           NOT NULL,
    [CODE_GROUP_ID]   INT           NOT NULL,
    [CODE_VALUE_DESC] VARCHAR (200) NOT NULL,
    [SRT_ORDER]       TINYINT       NULL,
    [PRIORITY_VALUE]  TINYINT       NULL,
    [IS_DEL_IND]      BIT           CONSTRAINT [DF__ARTIFACT___IS_DE__37461F20] DEFAULT ('FALSE') NOT NULL,
    [CREATED_DTE]     DATETIME      CONSTRAINT [DF__ARTIFACT___CREAT__383A4359] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]      VARCHAR (50)  NOT NULL,
    [LAST_UPDT_DTE]   DATETIME      NULL,
    [LAST_UPDT_BY]    VARCHAR (50)  NULL,
    [LOAD_ID]         INT           NULL,
    CONSTRAINT [PK_ARTIFACT_CODE_VALUE-CODE_VALUE_ID-CODE_GROUP_ID] PRIMARY KEY CLUSTERED ([CODE_VALUE_ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_ARTIFACT_CTRL_MASTER_CODE_GROUP_ID] FOREIGN KEY ([CODE_GROUP_ID]) REFERENCES [AM].[ARTIFACT_CODE_GROUP_VALUE] ([CODE_GROUP_ID]) ON UPDATE CASCADE
);

