CREATE TABLE [AM].[ARTIFACT_CODE_GROUP_VALUE] (
    [CODE_GROUP_ID]                  INT           NOT NULL,
    [CODE_GROUP_VALUE_DESC]          VARCHAR (500) NULL,
    [CODE_GROUP_VALUE_RELATED_FIELD] VARCHAR (50)  NULL,
    [IS_DEL_IND]                     BIT           CONSTRAINT [DF__ARTIFACT___IS_DE__070CFC19] DEFAULT ('FALSE') NOT NULL,
    [CREATED_DTE]                    DATETIME      CONSTRAINT [DF__ARTIFACT___CREAT__08012052] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]                     VARCHAR (50)  NOT NULL,
    [LAST_UPDT_DTE]                  DATETIME      NULL,
    [LAST_UPDT_BY]                   VARCHAR (50)  NULL,
    [LOAD_ID]                        INT           NULL,
    CONSTRAINT [PK_ARTIFACT_CODE_GROUP_VALUE-CODE_GROUP_ID] PRIMARY KEY CLUSTERED ([CODE_GROUP_ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [UNQ_ARTIFACT_CODE_GROUP_VALUE-CODE_GROUP_VALUE_DESC] UNIQUE NONCLUSTERED ([CODE_GROUP_VALUE_DESC] ASC) WITH (FILLFACTOR = 95)
);

