CREATE TABLE [AM].[ENVIRONMENT_VAR_SSISDB_MAPPING] (
    [ID]                        INT          NOT NULL,
    [FRAMEWORK_STATUS]          INT          NOT NULL,
    [SSISDB_STATUS]             INT          NOT NULL,
    [FRAMEWORK_STATUS_DESC]     VARCHAR (20) NOT NULL,
    [SSISDB_STATUS_DESC]        VARCHAR (20) NOT NULL,
    [CHG_FRAMEWORK_TO]          INT          NOT NULL,
    [CHG_FRAMEWORK_STATUS_DESC] VARCHAR (20) NULL,
    CONSTRAINT [PK-SSISDB_MAP-ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 95)
);

