CREATE TABLE [AM].[ENVIRONMENT_VAR_BATCH] (
    [SCHEDULE_TYPE_VALUE_ID] INT           NOT NULL,
    [SCHEDULE_NAME]          VARCHAR (100) NOT NULL,
    [RETRY_DELAY_MINUTES]    INT           NOT NULL,
    [SLA_TIME]               TIME (0)      NULL,
    [FORCE_COMPLETE]         BIT           NOT NULL,
    [HAS_MULTIPLE_BATCHES]   BIT           NOT NULL,
    [SCHEDULE_DESCRIPTION]   VARCHAR (100) NOT NULL,
    [IS_ENABLED_IND]         BIT           NOT NULL,
    [CREATED_DTE]            DATETIME      NOT NULL,
    [CREATED_BY]             VARCHAR (100) NOT NULL,
    [LAST_UPDT_DTE]          DATETIME      NULL,
    [LAST_UPDT_BY]           DATETIME      NULL,
    [IS_INCREMENTAL_LOAD]    BIT           NULL,
    CONSTRAINT [PK_ENV_VAR_BATCH-ID] PRIMARY KEY CLUSTERED ([SCHEDULE_TYPE_VALUE_ID] ASC) WITH (FILLFACTOR = 95)
);

