CREATE TABLE [AM].[PROCEDURE_ERROR_LOG] (
    [LOG_ID]        INT             IDENTITY (-1, -1) NOT NULL,
    [ERR_PROCEDURE] VARCHAR (128)   NOT NULL,
    [ERR_PLATFORM]  NVARCHAR (128)  NOT NULL,
    [ERR_NUMBER]    INT             NOT NULL,
    [ERR_LINE]      INT             NOT NULL,
    [ERR_SEVERITY]  INT             NOT NULL,
    [ERR_STATE]     INT             NOT NULL,
    [ERR_MESSAGE]   NVARCHAR (4000) NOT NULL,
    [USER_OSUSER]   VARCHAR (255)   NOT NULL,
    [CREATED_DTE]   DATETIME        CONSTRAINT [DF__PROCEDURE__CREAT__44CA3770] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_ERROR_LOG-LOG_ID] PRIMARY KEY CLUSTERED ([LOG_ID] ASC) WITH (FILLFACTOR = 95)
);

