CREATE VIEW [AM].[v_ALERTS_STATUS]
AS
SELECT
CASE CM.LAST_STATUS_CODE_VALUE_ID
        WHEN -1 THEN 'OPEN'
        WHEN 0 THEN 'OPEN'
        WHEN 1 THEN 'OPEN'
        WHEN 2 THEN 'CLOSED'
END AS 'ALERT_STATUS',
CASE CM.LAST_STATUS_CODE_VALUE_ID
        WHEN -1 THEN 'ERROR'
        WHEN 0 THEN 'INITIALIZED'
        WHEN 1 THEN 'RUNNING'
        WHEN 2 THEN 'COMPLETED SUCCESSFULLY'
END AS 'EXECUTION_STATUS',
CASE CM.LAST_STATUS_CODE_VALUE_ID
        WHEN -1 THEN 1
        WHEN 0 THEN  2
        WHEN 1 THEN  3
        WHEN 2 THEN  4
END AS 'SORT_ORDER'
,A.[ALERT_ID]
,A.[BATCH_DATE]
,0 [EXEC_TYPE]
,A.[ALERT_PRIORITY]
,A.[ALERT_CONTEXT]
,A.ART_CTRL_MASTER_ID [ARTIFACT_ID]
,A.[ARTIFACT_NAME]
,CV.CODE_VALUE_DESC [ARTIFACT_LAYER]
,0 [ARTIFACT_GROUP]
,0 [ARTIFACT_PROJECT]
,A.[RETRY_COUNT]
,A.[RETRY_THRESHOLD]
,A.[ERROR_MSG]
,A.[MSG_SOURCE]
,A.[CREATED_DTE]
FROM [AM].[ALERTS] A
INNER JOIN [AM].[BATCH_CTRL_MASTER] BS ON
A.BATCH_DATE >= BS.BATCH_DTE
INNER JOIN AM.ARTIFACT_CTRL_MASTER CM ON
A.ART_CTRL_MASTER_ID = CM.ART_CTRL_MASTER_ID
INNER JOIN AM.ARTIFACT_CODE_VALUE AS CV ON CM.ART_LAYER_VALUE_ID = CV.CODE_VALUE_ID INNER JOIN
AM.ARTIFACT_CODE_VALUE AS ST ON CM.LAST_STATUS_CODE_VALUE_ID = ST.CODE_VALUE_ID
Where LEN(ERROR_MSG) > 1 OR DATEDIFF(SECOND,A.CREATED_DTE, GETDATE()) > 60 AND (BS.END_DTE IS NULL)