

--[ART_BATCH_EXECUTION_PRIORITY_VALUE_ID], [ART_SCALE_VALUE_ID][PROCESS_TYPE_VALUE_ID][ART_BATCH_RETRY_THRESHOLD][BATCH_CYCLE]
CREATE VIEW [AM].[v_ARTIFACT_CTRL_MASTER]

AS 
SELECT
	   A.ART_CTRL_MASTER_ID, A.ART_NME, A.ART_PROCESS_DESC, A.ART_TYPE_VALUE_ID, C.CODE_VALUE_DESC AS 'TYPE_DESC', 
	   A.ART_SCALE_VALUE, A.ART_GROUP_VALUE_ID, E.CODE_VALUE_DESC AS 'GROUP_DESC',
	   A.ART_LAYER_VALUE_ID, F.CODE_VALUE_DESC AS 'LAYER_DESC',
	   A.SOURCE_SYSTEM_VALUE_ID, G.CODE_VALUE_DESC AS 'SOURCE_SYSTEM',
	   A.SCHEDULE_TYPE_VALUE_ID, B.CODE_VALUE_DESC as 'SCHEDULE_TYPE_DESC',
	   A.SCHEDULE_MODE_VALUE_ID, D.CODE_VALUE_DESC AS 'MODE_DESC',
	   A.SCHEDULE_RUN_TIME, A.ART_BATCH_RETRY_THRESHOLD, A.LOAD_TARGET_NME, A.LAST_SOURCE_NME,IS_ENABLED_IND,
	   A.CREATED_BY, A.CREATED_DTE, A.LAST_UPDT_BY, A.LAST_UPDT_DTE

	  FROM AM.ARTIFACT_CTRL_MASTER as A
		LEFT OUTER JOIN AM.ARTIFACT_CODE_VALUE AS B
			ON A.SCHEDULE_TYPE_VALUE_ID = B.CODE_VALUE_ID
		LEFT OUTER JOIN AM.ARTIFACT_CODE_VALUE AS C
			ON A.ART_TYPE_VALUE_ID = C.CODE_VALUE_ID
		LEFT OUTER JOIN AM.ARTIFACT_CODE_VALUE AS D
			ON A.SCHEDULE_MODE_VALUE_ID = D.CODE_VALUE_ID
		LEFT OUTER JOIN AM.ARTIFACT_CODE_VALUE AS E
			ON A.ART_GROUP_VALUE_ID = E.CODE_VALUE_ID
		LEFT OUTER JOIN AM.ARTIFACT_CODE_VALUE AS F
			ON A.ART_LAYER_VALUE_ID = F.CODE_VALUE_ID
		LEFT OUTER JOIN AM.ARTIFACT_CODE_VALUE AS G
			ON A.SOURCE_SYSTEM_VALUE_ID = G.CODE_VALUE_ID






