CREATE VIEW [AM].[v_ARTIFACT_DEPENDENCY]

AS

SELECT A.ART_CTRL_MASTER_ID, C.ART_NME, A.REFERENCED_CTRL_MASTER_ID,  D.ART_NME AS 'REF_ART_NME', A.DEPENDENCY_TYPE_VALUE_ID, B.CODE_VALUE_DESC, 
		A.DEPENDENCY_SEQUENCE, A.IS_ENABLED_IND, A.CREATED_DTE, A.CREATED_BY, A.LAST_UPDT_DTE, A.LAST_UPDT_BY
		FROM AM.ARTIFACT_DEPENDENCY AS A
			LEFT OUTER JOIN  AM.ARTIFACT_CODE_VALUE AS B
				ON A.DEPENDENCY_TYPE_VALUE_ID = B.CODE_VALUE_ID
			LEFT OUTER JOIN  AM.ARTIFACT_CTRL_MASTER AS C
				ON A.ART_CTRL_MASTER_ID = C.ART_CTRL_MASTER_ID
			LEFT OUTER JOIN  AM.ARTIFACT_CTRL_MASTER AS D
				ON A.REFERENCED_CTRL_MASTER_ID = D.ART_CTRL_MASTER_ID
		



