CREATE VIEW [AM].[v_ARTIFACT_PARAMETER]

AS 

SELECT ART_CTRL_MASTER_ID, PARM_ID, PARM_NME, PARM_VALUE_DATA_TYPE_CODE, PARM_CHAR_VALUE, PARM_INT_VALUE, PARM_DTE_VALUE
		, PARM_DESC, IS_ENABLED_IND, CREATED_DTE, CREATED_BY, LAST_UPDT_DTE, LAST_UPDT_BY, Coalesce(PARM_CHAR_VALUE, cast(PARM_INT_VALUE as varchar(100)), cast(PARM_DTE_VALUE as varchar(100))) as 'TYPE_VAL'
	FROM AM.ARTIFACT_PARAMETER
