

CREATE VIEW [AM].[v_CODE_VALUE_lOOKUP]

AS

SELECT A.CODE_VALUE_ID, A.CODE_VALUE_DESC, A.CODE_GROUP_ID, B.CODE_GROUP_VALUE_RELATED_FIELD, B.CODE_GROUP_VALUE_DESC, A.SRT_ORDER
	FROM AM.ARTIFACT_CODE_VALUE AS A
		 JOIN AM.ARTIFACT_CODE_GROUP_VALUE AS B
			ON A.CODE_GROUP_ID = B.CODE_GROUP_ID





