
CREATE VIEW [AM].[v_GET_DEPLOYMENT_INFO]
as

SELECT ACM.ART_CTRL_MASTER_ID, 
	PK.name AS 'ART_DEPLOYMENT_PATH',
	PRCV.CODE_VALUE_ID AS  'ART_PROJECT_VALUE_ID',
	PR.NAME AS 'ART_PROJECT_DESC',
	FCV.CODE_value_ID AS 'ART_FOLDER_VALUE_ID',
	F.name AS 'ART_FOLDER_DESC'

FROM AM.ARTIFACT_CTRL_MASTER ACM
	INNER JOIN SSISDB.CATALOG.PACKAGES PK  
		ON CONCAT(ACM.ART_NME, '.dtsx') = PK.name
	INNER JOIN  SSISDB.CATALOG.PROJECTS PR
		ON PK.project_id = PR.project_id
	INNER JOIN  SSISDB.CATALOG.folders F
		ON PR.folder_id = F.folder_id
	INNER JOIN AM.ARTIFACT_CODE_VALUE PRCV
		ON PRCV.CODE_VALUE_DESC = PR.name
		AND PRCV.CODE_GROUP_ID = 10
	INNER JOIN AM.ARTIFACT_CODE_VALUE FCV
		ON FCV.CODE_VALUE_DESC = F.name
		AND FCV.CODE_GROUP_ID = 11
