

CREATE VIEW [AM].[v_SPLASH_COUNTS]
AS
	SELECT CV.CODE_VALUE_DESC AS [ART TYPE], count(1) as [Count]
	FROM AM.ARTIFACT_CTRL_MASTER AS ACM 
		LEFT OUTER JOIN  AM.ARTIFACT_CODE_VALUE AS CV
			ON ACM.ART_TYPE_VALUE_ID = CV.CODE_VALUE_ID
	WHERE ACM.ART_TYPE_VALUE_ID > 10
	Group By CV.CODE_VALUE_DESC



