CREATE TABLE [TEST].[TESTING_CONTROL_ARTIFACT] (
    [TEST_ID]            INT          NOT NULL,
    [ART_CTRL_MASTER_ID] INT          NOT NULL,
    [IS_DEL_IND]         BIT          CONSTRAINT [DF_TESTING_DELIND] DEFAULT ('FALSE') NOT NULL,
    [CREATED_DTE]        DATETIME     CONSTRAINT [DF_TESTING_CRT_DTE] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]         VARCHAR (50) NOT NULL,
    [LAST_UPDT_DTE]      DATETIME     NULL,
    [LAST_UPDT_BY]       VARCHAR (50) NULL,
    [LOAD_ID]            INT          NULL,
    CONSTRAINT [PK_TESTING_ID-ART_ID] PRIMARY KEY CLUSTERED ([TEST_ID] ASC, [ART_CTRL_MASTER_ID] ASC) WITH (FILLFACTOR = 95)
);

