CREATE TABLE [TEST].[TESTING_CURRENT_TEST] (
    [TEST_ID]     INT           NOT NULL,
    [TEST_DESC]   VARCHAR (200) NOT NULL,
    [CREATED_DTE] DATETIME      NOT NULL,
    [CREATED_BY]  VARCHAR (50)  NOT NULL
);

