


--[ART_BATCH_EXECUTION_PRIORITY_VALUE_ID], [ART_SCALE_VALUE_ID][PROCESS_TYPE_VALUE_ID][ART_BATCH_RETRY_THRESHOLD][BATCH_CYCLE]
CREATE VIEW [CHG].[v_CHANGE_MASTER]

AS 
SELECT
	   A.CHG_ID, A.CHG_OPEN_DATE, A.CHG_CLOSE_DATE, A.CHG_OWNER, CHG_DESCRIPTION, A.IS_ACTIVE_IND, A.CREATED_DTE, A.CREATED_BY, A.LAST_UPDT_DTE, A.LAST_UPDT_BY 
       FROM CHG.CHANGE_MASTER as A




