


CREATE VIEW [DASH].[v_ALERTS_OPEN_FULL]
AS
SELECT 
       A.ALERT_ID
	  ,A.LOAD_ID
      ,A.EXECUTION_ID
      ,A.BATCH_DATE
      ,ART_TYPE_DESC
      ,A.ALERT_PRIORITY
      ,A.ALERT_CONTEXT
      ,A.ART_CTRL_MASTER_ID
      ,A.ARTIFACT_NAME
      ,A.RETRY_COUNT
      ,A.RETRY_THRESHOLD
      ,A.ERROR_MSG
      ,A.MSG_SOURCE
      ,A.CREATED_DTE
      ,A.MSG_UPDATED_DTE
	  ,CNT = 1
  FROM AM.ALERTS A
  Join (Select ART_CTRL_MASTER_ID, LAST_LOAD_ID From AM.ARTIFACT_CTRL_MASTER WHERE LAST_STATUS_CODE_VALUE_ID = -1) ACM
  ON ACM.ART_CTRL_MASTER_ID = A.ART_CTRL_MASTER_ID and ACM.LAST_LOAD_ID = A.LOAD_ID 
  WHERE ACM.ART_CTRL_MASTER_ID <> 998
 

 UNION ALL

 SELECT 
       A.ALERT_ID
	  ,A.LOAD_ID
      ,A.EXECUTION_ID
      ,A.BATCH_DATE
      ,'BATCH' as ART_TYPE_DESC
      ,A.ALERT_PRIORITY
      ,A.ALERT_CONTEXT
      ,A.ART_CTRL_MASTER_ID
      ,A.ARTIFACT_NAME
      ,A.RETRY_COUNT
      ,A.RETRY_THRESHOLD
      ,A.ERROR_MSG
      ,A.MSG_SOURCE
      ,A.CREATED_DTE
      ,A.MSG_UPDATED_DTE
	  ,CNT = 1
  FROM AM.ALERTS A
  Join (Select LOAD_ID From AM.BATCH_CTRL_MASTER WHERE STATUS_CODE_VALUE_ID = -1) BM
  ON BM.LOAD_ID = A.LOAD_ID 
  WHERE A.ART_CTRL_MASTER_ID = 998
 




