
--[ART_BATCH_EXECUTION_PRIORITY_VALUE_ID], [ART_SCALE_VALUE_ID][PROCESS_TYPE_VALUE_ID][ART_BATCH_RETRY_THRESHOLD][BATCH_CYCLE]
CREATE VIEW [TEST].[v_TESTING_MASTER]

AS 
SELECT
	   A.TEST_ID, A.TEST_OPEN_DATE, A.TEST_OWNER, TEST_DESCRIPTION, A.IS_DEL_IND, A.CREATED_DTE, A.CREATED_BY, A.LAST_UPDT_DTE, A.LAST_UPDT_BY 
       FROM TEST.TESTING_MASTER as A




