CREATE TABLE [CHG].[STAGE_CHANGE_CONTROL_ARTIFACT] (
    [CHG_ID]             INT          NOT NULL,
    [ART_CTRL_MASTER_ID] INT          NOT NULL,
    [IS_ACTIVE_IND]      BIT          DEFAULT ((0)) NOT NULL,
    [CREATED_DTE]        DATETIME     NOT NULL,
    [CREATED_BY]         VARCHAR (50) NOT NULL,
    [LAST_UPDT_DTE]      DATETIME     NULL,
    [LAST_UPDT_BY]       VARCHAR (50) NULL,
    [CREATED_ARC_DTE]    DATETIME     NULL,
    [LAST_CHG_LOAD_ID]   INT          NULL,
    CONSTRAINT [STG_PK_CHANGE_ARTIFACT] PRIMARY KEY CLUSTERED ([CHG_ID] ASC, [ART_CTRL_MASTER_ID] ASC) WITH (FILLFACTOR = 95)
);

