CREATE TABLE [dbo].[TEMP_TEST] (
    [ID]       INT          NOT NULL,
    [DOMAINID] VARCHAR (28) NULL,
    [FIXFLAG]  NUMERIC (1)  NULL,
    CONSTRAINT [PK_TEMP_TEST] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [PK_CNT] UNIQUE NONCLUSTERED ([ID] ASC, [DOMAINID] ASC)
);

